name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install pandoc
        run: |
          sudo apt-get update -qq
          curl https://github.com/jgm/pandoc/releases/download/3.4/pandoc-3.4-1-amd64.deb -L --output pandoc.deb
          sudo apt install ./pandoc.deb
          sudo apt-get install -y texlive

      - name: prepare build
        run: |
          mkdir build
          echo '<ul><li><a href="./solutions1.pdf">solutions 1</a></li><li><a href="./solutions2.pdf">solutions 2</a></li></ul>' > build/index.html
      
      - name: generate homework 1 solutions
        run: |
          pandoc -o build/solutions1.pdf homework_1/solutions.md --resource-path homework_1/
      
      - name: generate homework 2 solutions
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: homework_2
          root_file: solutions.tex
      
      - name: move solutions
        run: |
          mv homework_2/solutions.pdf build/solutions2.pdf

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
